// Master data codes — mirrors codes_dict.py

export const WAREHOUSE: Record<string, string> = {
  LK: "ลาดกระบัง",
  SR: "สระบุรี",
  KK: "ขอนแก่น",
  BK: "บางปะกง",
  XX: "ทุกคลัง / กลาง",
}

export const EXPENSE_TYPE: Record<string, { th: string; en: string; color: string }> = {
  PRT: { th: "อะไหล่", en: "Spare Parts", color: "#DEEAF1" },
  PM:  { th: "บำรุงรักษา", en: "Preventive Maintenance", color: "#E2EFDA" },
  LAB: { th: "ค่าแรง", en: "Labour", color: "#FFF2CC" },
  SVC: { th: "ค่าบริการ", en: "External Service", color: "#FCE4D6" },
  CLN: { th: "ค่าทำความสะอาด", en: "Cleaning", color: "#EDE7F6" },
  TRP: { th: "ค่าขนส่ง", en: "Transport / Towing", color: "#F0F0F0" },
  ACC: { th: "อุบัติเหตุ", en: "Accident Repair", color: "#FADBD8" },
}

export const SYSTEM_L1: Record<string, { th: string; en: string }> = {
  ENG: { th: "ระบบเครื่องยนต์", en: "Engine System" },
  COL: { th: "ระบบความเย็น/หม้อน้ำ", en: "Cooling System" },
  FUL: { th: "ระบบเชื้อเพลิง", en: "Fuel System" },
  TRN: { th: "ระบบส่งกำลัง", en: "Transmission & Drivetrain" },
  SUS: { th: "ระบบช่วงล่าง", en: "Suspension & Steering" },
  BRK: { th: "ระบบเบรก", en: "Brake System" },
  STR: { th: "ระบบพวงมาลัย", en: "Steering System" },
  ELC: { th: "ระบบไฟฟ้า", en: "Electrical System" },
  EXH: { th: "ระบบไอเสีย", en: "Exhaust & Emission" },
  TYR: { th: "ยางและล้อ", en: "Tyre & Wheel" },
  LUB: { th: "น้ำมันและสารหล่อลื่น", en: "Lubricants & Fluids" },
  MXS: { th: "ระบบโม่ผสม (Mixer)", en: "Mixer Drum System" },
  REF: { th: "ระบบทำความเย็น (Reefer)", en: "Refrigeration System" },
  PTO: { th: "ระบบ PTO", en: "Power Take-Off" },
  TRL: { th: "หางพ่วง/โดลลี่", en: "Trailer & Dolly" },
  BOD: { th: "ตัวถัง/โครงสร้าง", en: "Body & Structure" },
  SAF: { th: "อุปกรณ์ความปลอดภัย", en: "Safety Equipment" },
  CSM: { th: "วัสดุสิ้นเปลือง", en: "Consumables" },
  ACS: { th: "ระบบแอร์รถ (Cabin AC)", en: "Air Conditioning - Cabin" },
  LAB: { th: "ค่าแรงซ่อม", en: "Labour" },
  SVC: { th: "บริการภายนอก", en: "External Service" },
  CLN: { th: "ทำความสะอาด", en: "Cleaning" },
  TRP: { th: "ขนส่ง/ลากจูง", en: "Transport / Towing" },
}

export const SUB_ASSEMBLY_L2: Record<string, Record<string, { th: string; en: string }>> = {
  ENG: {
    OIL: { th: "ระบบน้ำมันเครื่อง", en: "Engine Oil System" },
    TOP: { th: "ฝาสูบและวาล์ว", en: "Cylinder Head & Valves" },
    BLK: { th: "บล็อกเครื่องยนต์", en: "Engine Block" },
    CRK: { th: "ข้อเหวี่ยงและก้านสูบ", en: "Crankshaft & Connecting Rod" },
    TIM: { th: "ระบบจังหวะ", en: "Timing System" },
    TRB: { th: "เทอร์โบชาร์จเจอร์", en: "Turbocharger" },
    MNT: { th: "ขายึดเครื่องยนต์", en: "Engine Mount" },
    VTC: { th: "ระบบ VTC/VVT", en: "Variable Timing" },
  },
  COL: {
    RAD: { th: "หม้อน้ำ", en: "Radiator" },
    WPP: { th: "ปั๊มน้ำ", en: "Water Pump" },
    TST: { th: "ฝาหม้อน้ำ/เทอร์โมสแตต", en: "Thermostat" },
    FAN: { th: "พัดลม/คลัทช์พัดลม", en: "Fan & Fan Clutch" },
    HSE: { th: "สายยาง/ข้อต่อ", en: "Hose & Coupling" },
    RES: { th: "ถังพักน้ำ", en: "Coolant Reservoir" },
    OIL: { th: "ระบบน้ำมันเครื่องหล่อเย็น", en: "Oil Cooler" },
  },
  FUL: {
    FLT: { th: "กรองเชื้อเพลิง", en: "Fuel Filter" },
    INJ: { th: "หัวฉีด/หัวฉีด Common Rail", en: "Injector" },
    PMP: { th: "ปั๊มเชื้อเพลิง", en: "Fuel Pump" },
    TNK: { th: "ถังน้ำมัน", en: "Fuel Tank" },
    CRL: { th: "ระบบ Common Rail", en: "Common Rail System" },
    SEP: { th: "กรองน้ำ/ตัวแยกน้ำ", en: "Water Separator" },
  },
  TRN: {
    CLT: { th: "คลัทช์", en: "Clutch" },
    GBX: { th: "เกียร์บ็อกซ์", en: "Gearbox" },
    PTF: { th: "เพลาส่งกำลัง", en: "Propeller Shaft" },
    DFF: { th: "เฟืองท้าย", en: "Differential" },
    AXL: { th: "เพลาล้อ", en: "Axle Shaft" },
    PTO: { th: "PTO", en: "Power Take-Off" },
  },
  SUS: {
    SPR: { th: "สปริง", en: "Spring" },
    SHK: { th: "โช้คอัพ", en: "Shock Absorber" },
    LNK: { th: "แขนช่วงล่าง/ลิงค์", en: "Control Arm & Link" },
    HUB: { th: "ดุมล้อ/ลูกปืนล้อ", en: "Hub & Wheel Bearing" },
    STB: { th: "กันโคลง", en: "Stabilizer Bar" },
    AIR: { th: "ถุงลมช่วงล่าง", en: "Air Suspension Bag" },
    CAB: { th: "ขายึดแคบ/ยึดห้องโดยสาร", en: "Cab Mount" },
  },
  BRK: {
    PAD: { th: "ผ้าเบรก", en: "Brake Pad / Lining" },
    DSC: { th: "จานเบรก", en: "Brake Disc / Drum" },
    CYL: { th: "แม่ปั๊มเบรก/ลูกปั๊ม", en: "Brake Cylinder" },
    LNE: { th: "สายเบรก/ท่อเบรก", en: "Brake Line / Hose" },
    AIR: { th: "ระบบเบรกลม", en: "Air Brake System" },
    SLK: { th: "สแล็กแอดจัสเตอร์", en: "Slack Adjuster" },
    HND: { th: "เบรกมือ", en: "Parking Brake" },
    ABS: { th: "ระบบ ABS", en: "ABS System" },
  },
  STR: {
    BOX: { th: "กระปุกพวงมาลัย", en: "Steering Box / Rack" },
    PWR: { th: "ปั๊มพาวเวอร์", en: "Power Steering Pump" },
    ROD: { th: "ลูกหมากคันชัก", en: "Tie Rod & Ball Joint" },
    COL: { th: "เสาพวงมาลัย", en: "Steering Column" },
    UNV: { th: "ข้อต่อสากล", en: "Universal Joint" },
  },
  ELC: {
    ALT: { th: "ไดชาร์จ", en: "Alternator" },
    STR: { th: "ไดสตาร์ท", en: "Starter Motor" },
    BAT: { th: "แบตเตอรี่", en: "Battery" },
    SNS: { th: "เซ็นเซอร์", en: "Sensor" },
    LGT: { th: "ไฟและหลอดไฟ", en: "Lights & Bulbs" },
    FSE: { th: "ฟิวส์และรีเลย์", en: "Fuse & Relay" },
    WRG: { th: "สายไฟ/ชุดสาย", en: "Wiring Harness" },
    ECU: { th: "กล่อง ECU/ECM", en: "ECU / Control Module" },
    CHG: { th: "ระบบชาร์จ", en: "Charging System" },
  },
  EXH: {
    MNF: { th: "ท่อร่วมไอเสีย", en: "Exhaust Manifold" },
    EGR: { th: "วาล์ว EGR", en: "EGR Valve" },
    DPF: { th: "กรอง DPF", en: "Diesel Particulate Filter" },
    SCR: { th: "ระบบ SCR/AdBlue", en: "SCR System" },
    CAT: { th: "ตัวเร่งปฏิกิริยา", en: "Catalytic Converter" },
    MFL: { th: "ท่อและท่อเก็บเสียง", en: "Muffler & Pipe" },
  },
  TYR: {
    TYR: { th: "ยางนอก", en: "Tyre" },
    RIM: { th: "วงล้อ/กระทะล้อ", en: "Rim / Wheel" },
    VLV: { th: "จุ๊บลมยาง", en: "Tyre Valve" },
    WST: { th: "น็อตและสตัด", en: "Wheel Stud & Nut" },
    TPM: { th: "เซ็นเซอร์ลมยาง TPMS", en: "TPMS Sensor" },
  },
  LUB: {
    EO:  { th: "น้ำมันเครื่อง", en: "Engine Oil" },
    GO:  { th: "น้ำมันเกียร์", en: "Gear Oil" },
    DFO: { th: "น้ำมันเฟืองท้าย", en: "Differential Oil" },
    HYD: { th: "น้ำมันไฮดรอลิก", en: "Hydraulic Oil" },
    BRK: { th: "น้ำมันเบรก", en: "Brake Fluid" },
    GRS: { th: "จาระบี", en: "Grease" },
    CLT: { th: "น้ำยาหม้อน้ำ", en: "Coolant" },
    PSF: { th: "น้ำมันพาวเวอร์", en: "Power Steering Fluid" },
    DEF: { th: "น้ำยา AdBlue/DEF", en: "DEF / AdBlue" },
  },
  MXS: {
    DRM: { th: "โม่/ถังผสม", en: "Mixer Drum" },
    RLR: { th: "ลูกกลิ้ง/รองรับโม่", en: "Drum Roller" },
    HYD: { th: "ระบบไฮดรอลิกโม่", en: "Mixer Hydraulic" },
    SLD: { th: "ซีลโม่", en: "Drum Seal" },
    GBX: { th: "เกียร์ขับโม่", en: "Mixer Gearbox" },
    WTR: { th: "ระบบน้ำ/ถังน้ำ", en: "Water System" },
    CHT: { th: "รางเทคอนกรีต", en: "Chute" },
  },
  REF: {
    CMP: { th: "คอมเพรสเซอร์ตู้เย็น", en: "Reefer Compressor" },
    EVP: { th: "อีวาพอเรเตอร์", en: "Evaporator" },
    CDN: { th: "คอนเดนเซอร์", en: "Condenser" },
    REF: { th: "น้ำยาแอร์", en: "Refrigerant" },
    BLW: { th: "มอเตอร์พัดลม", en: "Blower Motor" },
    SNS: { th: "เซ็นเซอร์อุณหภูมิ", en: "Temperature Sensor" },
    CTR: { th: "กล่องควบคุม", en: "Controller Unit" },
  },
  TRL: {
    KNG: { th: "คิงพิน", en: "King Pin" },
    FTH: { th: "จานหมุน (Fifth Wheel)", en: "Fifth Wheel" },
    LND: { th: "ขาตั้ง (Landing Gear)", en: "Landing Gear" },
    CON: { th: "ข้อต่อสายลม/สายไฟ", en: "Air Line / Electrical Connector" },
    AIR: { th: "ระบบเบรกลมหาง", en: "Trailer Air Brake" },
    LGT: { th: "ไฟท้ายหาง", en: "Trailer Light" },
  },
  BOD: {
    CBN: { th: "ห้องโดยสาร", en: "Cabin" },
    BDY: { th: "ตัวถัง/กระบะ", en: "Body Panel" },
    LGT: { th: "ไฟตัวถัง", en: "Body Light" },
    FRM: { th: "โครงช่วงล่าง/เฟรม", en: "Frame / Chassis" },
    MCH: { th: "กระจกและกลไก", en: "Mirror & Mechanism" },
    PNT: { th: "สี/งานพ่นสี", en: "Paint" },
    MRR: { th: "กระจกมองข้าง", en: "Side Mirror" },
  },
  SAF: {
    FEX: { th: "ถังดับเพลิง", en: "Fire Extinguisher" },
    TRI: { th: "สามเหลี่ยมฉุกเฉิน", en: "Emergency Triangle" },
    BLT: { th: "เข็มขัดนิรภัย", en: "Seat Belt" },
    CAM: { th: "กล้อง GPS/DVR", en: "Camera / GPS" },
  },
  CSM: {
    FLT: { th: "กรองอากาศ", en: "Air Filter" },
    BLT: { th: "สายพาน", en: "Belt" },
    PLG: { th: "หัวเทียน/หัวเผา", en: "Spark / Glow Plug" },
    WSH: { th: "แหวนซีล/ปะเก็น", en: "Washer / Gasket" },
  },
  LAB: {
    LAB: { th: "ค่าแรงซ่อม", en: "Repair Labour" },
  },
  SVC: {
    SVC: { th: "บริการภายนอก", en: "External Service" },
  },
  CLN: {
    CLN: { th: "ค่าทำความสะอาด", en: "Cleaning" },
  },
  TRP: {
    TOW: { th: "ค่าลากจูง", en: "Towing" },
    TRP: { th: "ค่าขนส่ง", en: "Transport" },
  },
  ACS: {
    CMP: { th: "คอมเพรสเซอร์แอร์", en: "AC Compressor" },
    CDN: { th: "คอนเดนเซอร์แอร์", en: "AC Condenser" },
    EVP: { th: "อีวาพอเรเตอร์", en: "Evaporator" },
    RDR: { th: "Receiver-Drier / ไดเออร์", en: "Receiver Drier" },
    EXV: { th: "วาล์ว膨張 / Expansion Valve", en: "Expansion Valve" },
    BLW: { th: "มอเตอร์พัดลมแอร์", en: "Blower Motor" },
    HSE: { th: "สายแอร์และข้อต่อ", en: "AC Hose & Fitting" },
    REF: { th: "น้ำยาแอร์ R134a/R1234yf", en: "Refrigerant" },
    SNS: { th: "เซ็นเซอร์แอร์", en: "AC Sensor" },
    CTR: { th: "แผงควบคุมแอร์", en: "AC Control Panel" },
  },
}

export const POSITION: Record<string, string> = {
  GN: "ทั่วไป",
  FN: "หน้า",
  RR: "หลัง",
  LF: "ซ้าย",
  RT: "ขวา",
  TP: "บน",
  BT: "ล่าง",
  CT: "กลาง",
  IN: "ใน",
  OT: "นอก",
  LF_FN: "ซ้ายหน้า",
  RT_FN: "ขวาหน้า",
  LF_RR: "ซ้ายหลัง",
  RT_RR: "ขวาหลัง",
  A1: "เพลา 1",
  A2: "เพลา 2",
  A3: "เพลา 3",
  AT: "ทุกเพลา",
}

export const UNIT: Record<string, string> = {
  PC: "ชิ้น", SET: "ชุด", PRS: "คู่", LTR: "ลิตร", KG: "กิโลกรัม",
  GRM: "กรัม", TYR: "เส้น", MTR: "เมตร", RLL: "ม้วน", BOX: "กล่อง",
  PKG: "แพ็ก", BTL: "ขวด", CAN: "กระป๋อง", JOB: "งาน", HR: "ชั่วโมง",
  DAY: "วัน", ML: "มิลลิลิตร", BAG: "ถุง", SHT: "แผ่น",
}

export const GRADE: Record<string, string> = {
  G1: "แท้ศูนย์นำเข้า (ซื้อศูนย์)",
  G2: "แท้ศูนย์ Local (ซื้อศูนย์)",
  G3: "เทียบ OEM หรือเทียบมี Brand",
  G4: "อะไหล่เก่าแท้ เซียงกง",
  G5: "เทียบ ไม่มี Brand ❌",
  G6: "อะไหล่เก่ารีบิ้ว โรงงาน",
  G7: "อะไหล่เก่ารีบิ้วเอง",
}

export const VEHICLE_TYPE: Record<string, { th: string; brand: string; engine: string }> = {
  MX10_ISZ: { th: "Mixer 10ล้อ Isuzu 6HK1",    brand: "ISUZU", engine: "6HK1-TC" },
  MX10_HIN: { th: "Mixer 10ล้อ Hino J08E",      brand: "HINO",  engine: "J08E-TV" },
  MX10_SAN: { th: "Mixer 10ล้อ Sany",            brand: "SANY",  engine: "Cummins" },
  MX6_ISZ:  { th: "Mixer 6ล้อ Isuzu 4HK1",      brand: "ISUZU", engine: "4HK1-TC" },
  MX6_HIN:  { th: "Mixer 6ล้อ Hino FC",          brand: "HINO",  engine: "J05E" },
  HD_HIN:   { th: "หัวลาก Hino 700",             brand: "HINO",  engine: "E13C" },
  HD_UD:    { th: "หัวลาก UD Quon",              brand: "UD",    engine: "GH13" },
  HD_ISZ:   { th: "หัวลาก Isuzu Giga",           brand: "ISUZU", engine: "6UZ1" },
  TK10_ISZ: { th: "รถบรรทุก 10ล้อ Isuzu",       brand: "ISUZU", engine: "6HK1" },
  TK10_HIN: { th: "รถบรรทุก 10ล้อ Hino",        brand: "HINO",  engine: "J08E" },
  TK6_ISZ:  { th: "รถบรรทุก 6ล้อ Isuzu",        brand: "ISUZU", engine: "4HK1" },
  TK6_HIN:  { th: "รถบรรทุก 6ล้อ Hino",         brand: "HINO",  engine: "J05E" },
  TK6_FOT:  { th: "รถบรรทุก 6ล้อ Foton",        brand: "FOTON", engine: "ISF3.8" },
  TK6_FAW:  { th: "รถบรรทุก 6ล้อ FAW",          brand: "FAW",   engine: "CA6DL" },
  TRL_SEM:  { th: "หางพ่วงกึ่งพ่วง",            brand: "-",     engine: "-" },
  TRL_DLY:  { th: "โดลลี่",                     brand: "-",     engine: "-" },
  TRL_TNK:  { th: "หางพ่วงถังน้ำ",              brand: "-",     engine: "-" },
  PU_TYT:   { th: "กระบะ Toyota Hilux/Revo",    brand: "TOYOTA",engine: "2GD-FTV" },
  PU_ISZ:   { th: "กระบะ Isuzu D-Max",          brand: "ISUZU", engine: "4JJ3" },
  VAN_TYT:  { th: "รถตู้ Toyota Commuter",      brand: "TOYOTA",engine: "1KD-FTV" },
  ISZ_ALL:  { th: "Isuzu (ทุกรุ่น)",            brand: "ISUZU", engine: "-" },
  HIN_ALL:  { th: "Hino (ทุกรุ่น)",             brand: "HINO",  engine: "-" },
}

export const EXPENSE_TYPES_NO_PRICE = ["LAB", "SVC", "CLN", "TRP", "ACC"]

export function buildSku(wh: string, type: string, l1: string, l2: string, l3: string, seq: number): string {
  const parts = l3 ? [wh, type, l1, l2, l3] : [wh, type, l1, l2]
  return `${parts.join("-")}-${String(seq).padStart(4, "0")}`
}
